### ISSUE TITLE
Update proxy settings after initializing 

### ISSUE THREAD

**Issue by itsezc** [whxaxes/tcp-proxy.js#2]
I would like additional functionality to change the remote host and port after the proxy is initialized.

**Comment by whxaxes** [comment]
Hi, there. I don't have time to implement this feature recently, PR is welcome

**Comment by itsezc** [comment]
Hello,

Thanks for the reply, I will be working on a few of my issues my self and do a pull request soon but I will not be adding this feature because this can be achieved already doing the following:

-> Ending the current proxy
-> Reinitiating a new proxy with the new details

Thanks
